apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dotnet-storage-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: dotnet-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
